trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'chemiliq-docker-hub-connection'
        repository: 'chemiliqdocket/currency-exchange-api-image'
        command: 'build'
        Dockerfile: '**/src/Services/CurrencyExchange/Dockerfile'
        buildContext: $(Agent.BuildDirectory)/src
        tags: '$(tag)'
